# Generated by Django 5.2 on 2025-04-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('stock', models.PositiveIntegerField(default=0, editable=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
